version: '3'

volumes:
  grocery_db_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - grocery_db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mynetwork

  db-migration:
    image: ghcr.io/amacneil/dbmate
    volumes:
      - ./apps/grocery-booking/db:/db
    command: up
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgres
    networks:
      - mynetwork

  grocery-booking:
    container_name: grocery-booking
    build:
      context: .
      dockerfile: ./apps/grocery-booking/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - 6000:6000
    networks:
      - mynetwork
    depends_on:
      - postgres
      - db-migration

networks:
  mynetwork:
    name: mynetwork
